name: Bug Report
description: File a bug report for the EphemeralNet daemon, CLI, or libephemeralnet API.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve EphemeralNet! Please fill out every section so we can reproduce the problem quickly.
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of EphemeralNet is affected?
      options:
        - CLI / eph
        - Daemon / control plane
        - Relay server
        - libephemeralnet API
        - Tests / CI
        - Documentation
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Affected version or commit
      description: Release tag (e.g., v1.0.1) or git commit hash.
      placeholder: v1.0.1
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Provide exact commands (e.g., `cmake -S . -B build`, `ctest --output-on-failure`, `eph fetch ...`). Include configuration files or manifests if relevant.
      placeholder: |
        1. Configure with cmake -S . -B build -G Ninja
        2. Run eph start --control-host 127.0.0.1
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior and logs
      description: Paste relevant output, stack traces, or attach files (use Gist if long). Redact secrets before sharing.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS version, compiler, CMake version, hardware, and any custom flags.
      placeholder: Windows 11, MSVC 19.39, CMake 3.27, Ninja 1.11
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions for duplicates.
          required: true
        - label: I have attached logs or reproduction steps that follow the template above.
          required: true
        - label: I agree to follow the Contributor Covenant Code of Conduct.
          required: true
