#!/usr/bin/env python3
"""Generate Docusaurus-ready docs from README sections."""
from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README_PATH = ROOT / "README.md"

DOC_SPECS = [
    {
        "filename": "01-intro.md",
        "frontmatter": """---
sidebar_position: 1
slug: /
title: Introduction
sidebar_label: Overview
---
""",
        "sections": [
            "Why EphemeralNet?",
            "High-Level Architecture",
            "Feature Highlights",
        ],
    },
    {
        "filename": "02-installation.md",
        "frontmatter": """---
sidebar_position: 2
title: Installation
slug: /installation
---
""",
        "sections": ["Quick Start Installation"],
    },
    {
        "filename": "03-quickstart.md",
        "frontmatter": """---
sidebar_position: 3
title: Quickstart
---
""",
        "sections": ["Usage", "Building from Source"],
    },
    {
        "filename": "04-reference.md",
        "frontmatter": """---
sidebar_position: 4
title: Reference Materials
---
""",
        "sections": ["Documentation", "Contributing & License"],
    },
]


def parse_sections(readme_text: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current = None
    heading_pattern = re.compile(r"^##\s+(.*)\s*$")
    for line in readme_text.splitlines(keepends=True):
        heading_match = heading_pattern.match(line)
        if heading_match:
            current = heading_match.group(1).strip()
            sections[current] = [line]
            continue
        if current:
            sections[current].append(line)
    return sections


def section_text(sections: dict[str, list[str]], title: str) -> str:
    if title not in sections:
        available = ", ".join(sections)
        raise KeyError(f"Section '{title}' not found in README (available: {available})")
    # Ensure trailing newline
    text = "".join(sections[title]).rstrip() + "\n"
    return text


def build_docs(output_dir: Path) -> None:
    WARNING_HEADER = """---
# -----------------------------------------------------------------------------
# 🛑 DO NOT EDIT THIS FILE MANUALLY! 🛑
#
# This file is AUTO-GENERATED from the README.md file in the root directory.
# Any changes made here WILL BE LOST the next time the docs are regenerated.
#
# To update this content, edit the corresponding section in README.md and run
# the generation script: scripts/generate_docs.py
# -----------------------------------------------------------------------------
"""

    readme_text = README_PATH.read_text(encoding="utf-8")
    sections = parse_sections(readme_text)

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    for spec in DOC_SPECS:
        body_parts = [section_text(sections, title) for title in spec["sections"]]
        body = "\n\n".join(part.rstrip() for part in body_parts) + "\n"
        content = WARNING_HEADER + "\n" + spec["frontmatter"].strip() + "\n\n" + body
        target = output_dir / spec["filename"]
        target.write_text(content, encoding="utf-8")
        print(f"Wrote {target.relative_to(ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(ROOT / "docs-generated"), help="Destination directory for generated docs")
    args = parser.parse_args()
    build_docs(Path(args.output))


if __name__ == "__main__":
    main()
