# Minimal warning set for EphemeralNet targets
function(ephemeralnet_enable_warnings target)
    set(oneValueArgs)
    set(multiValueArgs)
    set(options TREAT_AS_ERRORS)
    cmake_parse_arguments(PARSE_ARGV 1 WARN "${options}" "${oneValueArgs}" "${multiValueArgs}")

    if(MSVC)
        target_compile_options(${target} PRIVATE /permissive- /W4)
        if(WARN_TREAT_AS_ERRORS)
            target_compile_options(${target} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if(WARN_TREAT_AS_ERRORS)
            target_compile_options(${target} PRIVATE -Werror)
        endif()
    endif()
endfunction()
